### PR TITLE
Migration to GitHub Actions 

### PR DESCRIPTION
**Pull request by sunkan**
Here is first working draft of migration to github actions

I hade to disable nightly builds because of [phpspec/prophecy](https://github.com/phpspec/prophecy/commit/765cd5d5d237525f8bbadaec5dc161c83a369119#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) not supporting nightly.

I also added a build step to verify that it works with ` --prefer-lowest` composer option

You can see the output from the last build here
https://github.com/sunkan/openapi-psr7-validator/actions/runs/415797193

### CODE REVIEW

**Comment by scaytrase** [comment]
> I hade to disable nightly builds because of phpspec/prophecy not supporting nightly.

That's the purpose of allow-failures for nighly. To keep track of things that are not working.Is it possible to have it, but non-blocking?

**Comment by sunkan** [comment]
@scaytrase 

I've updated the action with nightly that is none blocking.

you can see the output here https://github.com/sunkan/openapi-psr7-validator/actions/runs/415935071

I also reworked the highest/lowest version testing

**Comment by scaytrase** [comment]
looks nice

**Comment by sunkan** [comment]
I think this is finished to merge if you approve

**Comment by scaytrase** [comment]
Thanks @sunkan

**Pull request merged**
