### PR TITLE
Fix TypeError in case of empty string a Content-Type

### PR DESCRIPTION
**Pull request by hpatoio**
See #60 for details

### CODE REVIEW

**Comment by scaytrase** [comment]
Nice catch! Can you please apply `vendor/bin/phpcbf` in order I can merge this?

**Comment by hpatoio** [comment]
I setup the hook as described in the doc ... but there were some errors because I'm using a docker. Fixing manually.

**Comment by hpatoio** [comment]
Pushed CS fixes. If is ok I can squash and merge.

**Comment by scaytrase** [comment]
Thanks @hpatoio !

**Pull request merged**
