### PR TITLE
Support Status Code Ranges 2XX, 3XX, 4XX, 5XX

### LINKED ISSUE #158: Support Pattern Response Status Codes (2XX, 3XX, 4XX, and 5XX)
According to Open Api Specification 3.0.0 and above 
the Response Object alows to describe Error Responses in 
https://spec.openapis.org/oas/v3.0.0.html#patterned-fields-0

but the validation currently fails for schemas describing Status ranges.

### PR DESCRIPTION
**Pull request by wolffc**
fixes #158

### CODE REVIEW

**Comment by scaytrase** [comment]
Loogs good, but can you please provide a test case for new feature?

**Comment by scaytrase** [comment]
Tests are failing

**Comment by wolffc** [comment]
i will take care of fixin the issues and providing a test case

**Comment by wolffc** [comment]
@scaytrase added test and seems to be passing scutinzer let me know if anything else is still missing.

**Review by scaytrase — APPROVED** [review]
LGTM 👍

**Comment by scaytrase** [comment]
Thanks @wolffc !

**Comment by scaytrase** [comment]
https://github.com/thephpleague/openapi-psr7-validator/releases/tag/0.18

**Pull request merged**
