### PR TITLE
Use devizzent/cebe-php-openapi to be compatible with OpenApi 3.1

### PR DESCRIPTION
**Pull request by DEVizzent**

### CODE REVIEW

**Comment by scaytrase** [comment]
@cebe hello, please, can you give us maintenance status for `cebe/php-openapi` ? Switching deps to a fork is a last resort measure but as far as I see project is not being developed for a long time. Also I'd rather suggest to give some limited permissions in order to maintain existing source code instead of switching to the fork road

https://github.com/cebe/php-openapi/pull/128
https://github.com/cebe/php-openapi/branches

**Comment by DEVizzent** [comment]
@scaytrase I agree your comment.
Open Api 3.1 was released almost 2 years ago(2021-02-18).
Some people came to the MR to bring some help. But there are no activity from cede in this project since April 2022. I did it for unblocking the situation. There are people interested in contribute to the library but it seems there are no way.

**Comment by DEVizzent** [comment]
@scaytrase How many time do we must wait for an answer? @cebe had some contributions in github during end of January and beginning of February but he ignored the project, all the comments and PRs.

There are a lot of people interested in contribute to that project, but nobody has permissions to manage PRs...

**Comment by scaytrase** [comment]
Yea, thanks for reminder, I've just got a little too busy last time, sorry. I think we can merge this

**Comment by scaytrase** [comment]
Thanks @DEVizzent !

**Pull request merged**
