### PR TITLE
test(typeMismatch): Add test on querystring parameters with array values of number

### PR DESCRIPTION
**Pull request by Identity-labs**
https://github.com/thephpleague/openapi-psr7-validator/issues/140

### CODE REVIEW

**Comment by scaytrase** [comment]
Please run `vendor/bin/phpcbf`. I see one failing test but it seems irrelevant to new code, looks like some changes in latest dependencies

**Comment by Identity-labs** [comment]
Code style is fixed.
Yes one test is failing, but on master too.

**Comment by scaytrase** [comment]
I wil deal it by myself later, don't worry

**Review by scaytrase — APPROVED** [review]
LGTM 👍

**Comment by scaytrase** [comment]
Thanks @Identity-labs !

**Comment by Identity-labs** [comment]
Thanks :) A tag will be created ?

**Comment by scaytrase** [comment]
Sure, I'm checking failing test now and will release a tag after I fix it or decide it's non-blocking

**Comment by scaytrase** [comment]
@Identity-labs here it is https://github.com/thephpleague/openapi-psr7-validator/releases/tag/0.16.2 I've considered this a bugfix

**Pull request merged**
