### PR TITLE
Update `doctrine/coding-standard` to 8.x

### PR DESCRIPTION
**Pull request by canvural**
This PR updates `doctrine/coding-standard` to 8.x

### CODE REVIEW

**Review by scaytrase — APPROVED** [review]
Point for discussion. Should we keep rules when update changes them or we just strictly follow upstream ruleset.
For example `) : typehint`. We can change local ruleset in order to keep codebase the same as we used to work with, or we just want have a consistent codebase without any general requirements on how it looks.

I'm personally OK with new codestyle, I like `): typehint` format.

**Comment by sunkan** [comment]
I think it's easier to just follow the upstream change otherwise after a couple of update you have your very own code style :smile: 

Also I prefer the `): typehint` format. It's the same we use at work

**Comment by scaytrase** [comment]
> you have your very own code style
And it's exact the same as at the start of the project, that's the point. I'm ok with ANY codestyle, even very own one. But between stable own one and changing foreign I'd rather choose stable own.

**Comment by sunkan** [comment]
Yes I see your point.

I would say that we should probably only think about changing code style with major versions. 

But since we haven't reached version 1 yet. I'm still fine with this update

**Comment by scaytrase** [comment]
I think codestyle has nothing to do with versioning since any codestyle change is non-breaking change. You really don't care which codestyle class you are extending or implementing )
Codestyle itself is important only for developing community, not for users

**Comment by scaytrase** [comment]
@canvural can you please reapply CS fixes to current master? I'll merge this after

**Comment by canvural** [comment]
@scaytrase Done :+1:

**Comment by scaytrase** [comment]
Thanks!

**Pull request merged**
